// src/app/components/ui/footer/footer.component.ts
import { Component } from '@angular/core';
import { faGithub, faTwitter } from '@fortawesome/free-brands-svg-icons';
import { faUser, faCoffee } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {
  faGithub = faGithub;
  faTwitter = faTwitter;
  faUser = faUser;
  faCoffee = faCoffee;

}

<footer>
  <div class="social-icons">
    <a href="https://www.berkankutuk.dk" target="_blank">
      <fa-icon [icon]="faUser"></fa-icon>
    </a>
    <a href="https://www.twitter.com/berkanktk" target="_blank">
      <fa-icon [icon]="faTwitter"></fa-icon>
    </a>
    <a href="https://www.github.com/berkanktk" target="_blank">
      <fa-icon [icon]="faGithub"></fa-icon>
    </a>
    <div style="display: inline-block" class="coffee">
      <a href="https://www.buymeacoffee.com/berkanktk" target="_blank" title="Buy me a coffee?" >
        <fa-icon [icon]="faCoffee"></fa-icon>
      </a>
      </div>
  </div>
</footer>

// src/lib/components/Footer.svelte
<script>
  import { FontAwesomeIcon } from "@fortawesome/svelte-fontawesome";
  import { faGithub, faTwitter } from "@fortawesome/free-brands-svg-icons";
  import { faUser, faCoffee } from "@fortawesome/free-solid-svg-icons";
</script>

<footer>
  <div class="social-icons">
    <a
      href="https://www.berkankutuk.dk"
      target="_blank"
      aria-label="Visit my website"
    >
      <FontAwesomeIcon icon={faUser} />
    </a>
    <a
      href="https://www.twitter.com/berkanktk"
      target="_blank"
      aria-label="Follow me on Twitter"
    >
      <FontAwesomeIcon icon={faTwitter} />
    </a>
    <a
      href="https://www.github.com/berkanktk"
      target="_blank"
      aria-label="View my GitHub profile"
    >
      <FontAwesomeIcon icon={faGithub} />
    </a>
    <div class="coffee">
      <a
        href="https://www.buymeacoffee.com/berkanktk"
        target="_blank"
        title="Buy me a coffee?"
        aria-label="Buy me a coffee"
      >
        <FontAwesomeIcon icon={faCoffee} />
      </a>
    </div>
  </div>
</footer>

<style>
  footer {
    position: fixed;
    bottom: 0;
    right: 0;
    color: #fff;
    padding: 20px;
    display: flex;
  }

  .social-icons {
    display: flex;
  }

  .social-icons a {
    color: #fff;
    margin-right: 20px;
    font-size: 20px;
  }

  .social-icons a:hover {
    color: #c96;
  }

  .coffee {
    animation: shake 1.75s infinite;
  }

  @keyframes shake {
    0% {
      transform: translate(0, 0);
    }
    25% {
      transform: translate(0, 0);
    }
    50% {
      transform: translate(0, -2px);
      transition: transform 330ms ease-in-out;
    }
    75% {
      transform: translate(0, 0);
    }
    100% {
      transform: translate(0, 0);
    }
  }

  a[title]:hover::after {
    content: attr(title);
    font-size: 18px;
    position: absolute;
    top: -50px;
    left: -50px;
  }
</style>
